### ISSUE TITLE
Display of heartrate in profile - bug in layout

### ISSUE THREAD

**Issue by sfuchs79** [subsurface/subsurface#1162]
### Describe the issue:

- [x] Bug
- [ ] Change request
- [ ] New feature request
- [ ] Discussion request

### Issue long description:

There are min. two serious bugs in the display of the heartrate in the profile:
- The y-axis tics are totaly wrong:
![grafik](https://user-images.githubusercontent.com/25316050/37307500-786fce08-263b-11e8-8f5b-906e96dd9086.png)
- When heatmap is on it's covering the heartrate graph:
![grafik](https://user-images.githubusercontent.com/25316050/37307559-a122ae60-263b-11e8-8194-9ea3c938e56b.png)

### Operating system:

Windows 10

### Subsurface version:

Latest master 4.7.7-something

### Mentions:

@p-neves

**Comment by p-neves** [comment]
I can confirm the same happens in Linux with latest master
The font is ok when one zooms in on the graphic, but is too big when you zoom out...

![heartrate_y_axis](https://user-images.githubusercontent.com/16014958/37314204-ccec213e-264a-11e8-8e2c-e96c5562ddd9.png)

**Comment by jbygdell** [comment]
Fully known issue.. based on the fact that the scaling of the different components in the profile is not dynamic.
Displaying all components at the same time results in a very messy profile.
Building a code that can handle every single combination is rather tedious with a lot of if statements that need to work together. And since only 1 or 2 DC can actually deliver HR data the priority has been very low on this.

**Comment by sfuchs79** [comment]
@jbygdell 
I agree with you that displaying everything at the same time may not be useful at all.
But nevertheless we could improve it maybe simple by switching heatmap off when switching heartrate on and vice versa.
And the tics are easy to fix. Maybe let's just change from step value of 10 to 25 or 50.

**Comment by jbygdell** [comment]
A better way to fix the set size is to set the y-axis scale from lowest value-5 to max value+5, not 0 to max rounded up as it is now.
