### ISSUE TITLE
Subsurface-mobile: don't start map in London

### ISSUE THREAD

**Issue by dirkhh** [subsurface/subsurface#1182]
### Describe the issue:

- [ ] Bug
- [ ] Change request
- [ ] New feature request
- [x] Discussion request

### Issue long description:

I think it would be better to not start the first transition in London, but to recognize "no previous location" and simply start "out" a couple of zoom levels from the first location for which the map button was pressed...

### Operating system:

Android (maps still don't work on iOS)

### Subsurface version:

latest beta: 4.7.7.145
### Steps to reproduce:

open dive log
tap on map button for a dive with gps info
### Current behavior:

show London, zoom out, move, zoom in
### Expected behavior:

start above the location of that dive, but zoomed out 4x or 8x, then zoom in
### Mentions:

@neolit123

**Comment by neolit123** [comment]
> show London, zoom out, move, zoom in

i forgot about this problem. i think the correct way to approach this to always initialize the map with maximum-zoom out seeing the whole globe. this would require the least changes.

^ edit: actually that doesn't work well, because we have a "sticky zoom" (that Linus introduced) and no zoom-in is happening if the map is started zoomed out completely.
