### ISSUE TITLE
Support for different cloud accounts, to be able to test across devices.

### ISSUE THREAD

**Issue by janiversen** [subsurface/subsurface#1273]
### Describe the issue:

- [ ] Bug
- [ ] Change request
- [x ] New feature request
- [ ] Discussion request

### Issue long description:

I have right now 3 versions installed on my iPad and iPhone (release, testFlight, myVersion)
And 3 versions installed on my Mac (release, myVersion).

I have a user in the cloud, which contains my real dives, I added a new user to have test dives. 

It would be handy to assign a user to each of software packages (seems to me, we could do it by not only having different names for the package, but also use this name to store the local data.

If it is seen as a good idea, then I will go searching in the sources to implement something like this (should be rather easy, and a good way to learn more of source).

### Operating system:

mac, iOS

**Comment by dirkhh** [comment]
I'm not 100% sure what you are asking for.
On your Mac, you can simply start the app from the command line (which allows you to see debug output) and ask it to use a different configuration:
`./Subsurface.app/Contents/MacOS/Subsurface --user=test`
which will use a different configuration.
It still will use the same local caches (as those are based on your macOS user ID, not the `--user` parameter.
As I said, I'm not quite sure what you are asking for, so maybe this isn't even what you are looking for. And I completely don't understand what you are asking for wrt to iPhone / iPad.

**Comment by janiversen** [comment]
Sorry for my bad English :-)

I want to have 1 user/cloudstorage/settings for the release version where I keep my real dives.
1 user/cloudstorage/setting for the "myVersion" (normally latest master) where I can have test dives, that I can manipulate freely.
However since I do a lot of crossplatform testing, I need this for both iOS and Mac.

In essence I want to keep the test setup isolated from the release, not to endanger my real dives.

Hope that makes it a bit clearer.

**Comment by dirkhh** [comment]
Yes, that's a lot clearer. On the Mac that's exactly what you can do with the `--user=...` option. That's how I use things all the time. On iOS... that's something we'd have to add somewhere. And I'm not sure what the best approach would be. Maybe an option under `Developer` to use alternative settings? Not sure. At this point I just manually switch on Android/iOS...

**Comment by janiversen** [comment]
Thanks, good advice

**Comment by dirkhh** [comment]
While I'm of course OK with closing this, I think it would be just a few minutes of work to implement a very simplistic way to do this - you'd have to keep things in sync manually, but...

Let's assume you use `--user=test` on the desktop and use a different cloud account for that.
How about I add a trivial little change where in the Developer menu you could select to `use alternate settings file`. Once you enable that we re-open the settings with a different name, you have to manually enter that same testing account name there, and then you can switch between the two _worlds_ by simply toggling this option?
Oh, crud. It is a bit more complicated because then you'd need to persist that setting. So no, that's not a great idea.

OK, different idea. This wouldn't work for the TestFlight app (as that is an "official binary" which usually after some testing simply gets "promoted" to become the new current version), but for your test .ipa that you build at home... we could include the BUNDLE_ID in the path when we open the settings, so your home-built app would use different settings.

Would that be useful? Or is this all just too much hassle?

**Comment by dirkhh** [comment]
Happy to let you work on this! I'm reopening the issue - in your commit message simply have a line
```
Fixes #1273
```
and then when we merge this the issue gets closed again :-)

**Comment by janiversen** [comment]
out-trixed myself. Using my Apple ID (the new environment variable) solves the problem on iOS, and your solution is elegant on Mac. So (sadly enough) no need to dig in sources.
