### ISSUE TITLE
New filter model causing new warnings on MAC.

### ISSUE THREAD

**Issue by janiversen** [subsurface/subsurface#1619]
### Describe the issue:

- [ x] Bug
- [ ] Change request
- [ ] New feature request
- [ ] Discussion request

### Issue long description:

When compiling on Mac for Mac or iOS the following warnings are issues quite a lot of times:

In file included from /Users/jani/develop/src/subsurface/desktop-widgets/divelistview.cpp:8:
/Users/jani/develop/src/subsurface/./qt-models/filtermodels.h:42:16: warning: 'flags' overrides a
      member function but is not marked 'override' [-Winconsistent-missing-override]
        Qt::ItemFlags flags(const QModelIndex &index) const;
                      ^
In file included from /Users/jani/develop/src/subsurface/desktop-widgets/divelistview.cpp:8:
/Users/jani/develop/src/subsurface/./qt-models/filtermodels.h:43:11: warning: 'data' overrides a
      member function but is not marked 'override' [-Winconsistent-missing-override]
        QVariant data(const QModelIndex &index, int role = Qt::DisplayRole) const;
                 ^
In file included from /Users/jani/develop/src/subsurface/desktop-widgets/divelistview.cpp:8:
/Users/jani/develop/src/subsurface/./qt-models/filtermodels.h:44:7: warning: 'setData' overrides a
      member function but is not marked 'override' [-Winconsistent-missing-override]
        bool setData(const QModelIndex &index, const QVariant &value, int role = Qt::EditRole);
             ^

Remark: removed lines to make the issue shorter

This is something new that was not present a couple of weeks ago.

### Operating system:

osx newest, xcode newest, Qt 11.1

### Expected behavior:

no warnings.

**Comment by bstoeger** [comment]
Gah. At this point I would opt for passing `-Wno-inconsistent-missing-override` to clang, as this warning actually *hinders* us adding `override`s.

**Comment by janiversen** [comment]
sounds wrong, if these were to be overwritten, they would have been marked so. Supressing warnings just because we use the system different does not sound like a correct implementation.

But of course if we do not care about these kind of warnings, change the makefiles.

**Comment by bstoeger** [comment]
>  if these were to be overwritten, they would have been marked so.

I am not sure if you get the point of the `override` keyword? The functions *are* overridden, since they have the same function signature as the virtual functions in the base class. By adding the `override` keyword failing to do so (because we get the signature subtly wrong) results in a hard compilation error.

This is generally considered to be a good thing, as failure to override might result in more-or-less subtle bugs.

The `-Winconsistent-missing-override` flag warns us if we override functions but don't mark them as such. But it only does so if at least one of the member functions is marked override. Hence the "inconsistent". This is well-intended, but unfortunately counter-productive, as it makes adding `override` more painful. Matter of fact, we lost all overrides due to this warning.

**Comment by bstoeger** [comment]
Is this fixed with #1622? Can we close?
(Do the Travis builds disappear for commited PRs, or am I just not seeing them anymore?)

**Comment by bstoeger** [comment]
Didn't find the word "marked" in this log: https://api.travis-ci.org/v3/job/425059608/log.txt
Closing. Please reopen if I'm mistaken.
