### ISSUE TITLE
subsurface-mobile App crashes downloading dives from dive computer

### ISSUE THREAD

**Issue by satoschu** [subsurface/subsurface#1704]
### Describe the issue:

- [x] Bug
- [ ] Change request
- [ ] New feature request
- [ ] Discussion request

### Issue long description:

If I try to download dives from the Oceanic VT4.1 with FTDI the subsurface mobile App crashes.

### Operating system:

Android 6.0.1

### Subsurface version:

2.1.2

### Steps to reproduce:

1. Connect dive computer to phone by usb
2. App opens automatically in the download tab
3. Choosing interface and computer type
4. Click on download
5. App closes

Crash log was send by email.

**Comment by hgraefe** [comment]
Same problem here on Huawei P20 lite with Android 8.0.0 and my brandnew OTG adapter. I tried the Suunto Gekko and Zoop. Immediate crashing. My phone tries to charge the USB device instead of receiving the data.

**Comment by dirkhh** [comment]
A new app version 2.1.3 has been pushed to the Android Play Store and should be available by now (Google is MUCH faster than Apple, but timing is still somewhat variable). That version should fix this FTDI crash.

**Comment by hgraefe** [comment]
Very Fast! No more crashes but unfortunately no download. My phone switch always back to USB charging and not to data transfer. Why?

**Comment by dirkhh** [comment]
Because of the way we try to talk to FTDI devices. This is an issue in the code that we use that conflicts with certain SELinux (i.e., security) settings, that some Android vendors have implemented.
This is caused by the cross-platform nature of Subsurface - we are reusing the same code (more or less) across Linux, Mac, Android, Windows and iOS.
We need to add special handling on Android to talk to devices "the ~~Java~~ _Android_ way", but none of the developers has found the time (and energy, and motivation) to make this happen.
As a result right now FTDI downloads work on some Android devices and don't work on others :-(

**Comment by glance-** [comment]
s/the Java way/the Android way/
