### ISSUE TITLE
Version 4.6.0 crashes exporting to divelogs.de

### ISSUE THREAD

**Issue by grosengarten** [subsurface/subsurface#172]
Subsurface 4.6.0 crashes when exporting a selection of dives to divelogs.de.  This bug seems to have been introduced by this version- on the previous version exporting to divelogs.de worked fine.

I'm running OS X Yosemite and the logs were imported from a Shearwater Perdix.

**Comment by dirkhh** [comment]
I tried to reproduce this and for me it works fine (admittedly, tested on El Capitan as I don't have a access to a Mac running Yosemite right now). Can you send me in email an XML export of your dive data file so I can try to reproduce the problem here?

**Comment by fedMasias** [comment]
I tried last night and was able to reproduce on El Capitan, using the official binary download. Was also crashing when trying to export all. 

I've never exported to divelogs before, if that makes a difference

**Comment by dirkhh** [comment]
Can you send me the crash report (as produced by MacOS) - it might help a little. Or send me your XML file... I'd love to figure out what's going wrong here

**Comment by dirkhh** [comment]
I believe I identified the build problem that caused this. The libzip-1.1.2 built from current Homebrew apparently doesn't work correctly under certain circumstances - I now built the library manually and packaged that replacement .dylib with an otherwise unchanged Subsurface 4.6. I have replaced the Subsurface-4.6.0.dmg on our download page with an updated version and using that @fezzington was no longer able to reproduce the crash (I was never able to reproduce it). 
@grosengarten would you please test that this new DMG works for you as well and then close this issue?
Thanks

**Comment by grosengarten** [comment]
Sorry, where can I find the DMG?

**Comment by fedMasias** [comment]
@grosengarten , the new DMG can be found on the Subsurface Website, on the [downloads page](https://subsurface-divelog.org/download/) .

**Comment by grosengarten** [comment]
Yes, thanks-  found it.  Indeed the issue looks to have been fixed.  Thanks!

**Comment by dirkhh** [comment]
Thank you so much for reporting back - really appreciated. Let us know if you run into other issues :-)
