### ISSUE TITLE
Calculate/Show average temperature

### ISSUE THREAD

**Issue by xsw21qay** [subsurface/subsurface#2310]
### Describe the issue:

- [ ] Bug
- [ ] Change request
- [x] New feature request
- [ ] Discussion request

### Issue long description:
As user of subsurface mobile I would like to see the average temperature of the dive.

A running average graph similar to the average depth graph would be great.

### Operating system:

Android 9

Xiaomi MI 9

### Subsurface version:

4.9.3.106

Yes

Official release

### Current behavior:

Average temperature is missing

### Expected behavior:

Average temperature is shown as running average in the graph

**Comment by dirkhh** [comment]
There's the eternal trade-off between more features and visual clarity.
This is the first time we've seen a request for average temperature. Personally, I don't see how I would use that. Whether or not I'm cold on a dive depends on the temperature at the depth at which I am spending time. Similarly, dives with inverted temperature profile will feel very differently from those with traditional ones (the deeper, the colder). Yet they may have the same average depth.
Also, most dive computers will show significantly too high temperatures for the first few minutes because the temperature sensors respond slowly and will still be impacted by the surface temperature.
All in all, I don't think this is a request we are going to follow up on.
Of course, this is open source software, so it shouldn't be too hard to implement this yourself if this is something you really feel you have to have.
