### ISSUE TITLE
Github actions active on forked instances, leading to a lot of errors.

### ISSUE THREAD

**Issue by janiversen** [subsurface/subsurface#2423]
### Describe the issue:

- [x ] Bug
- [ ] Change request
- [ ] New feature request
- [ ] Discussion request

### Issue long description:

The new GitHub actions seems to be active on forked copies as well as the original subsurface, this leads to a lot of errors when doing "git push" to the forked copy.

People who works directly on the original subsurface or a branch, do probably not experience this problem. Seems to be limited to contributors that cannot work on a branch, and therefore work on a forked copy.

![Captura de pantalla 2019-12-06 a las 10 12 01](https://user-images.githubusercontent.com/6185391/70311181-6a96cd80-1811-11ea-8bb0-ea85ccfe21ec.png)

Please only run GitHub actions on the original subsurface, or advice how to block Github actions on a forked copy, without disrupting the original.

**Comment by glance-** [comment]
Almost no development happens on branches in the main repo, most happens in forked repos. (Dirk sometimes uses branches in the main repo for testing things).

You can turn github actions off for your own fork, going settings -> actions -> "Disable Actions for this repository ".

Also, we should rather fix so that all the actions works as expected in forked repos to.
