### ISSUE TITLE
No Dives appear in mobile client from cloud account

### ISSUE THREAD

**Issue by cetra3** [subsurface/subsurface#2774]
### Describe the issue:

- [x] Bug
- [ ] Change request
- [ ] New feature request
- [ ] Discussion request

### Issue long description:

I have 144 dives logged in subsurface which are visible at https://cloud.subsurface-divelog.org/ and also on the desktop app but don't appear on the mobile client

### Operating system:

Android, Samsung Galaxy S8 and also Samsung Galaxy Tab S5e do not work

### Subsurface version:

Version: 3.0.3 4.9.3.1442

It was previously syncing fine but noticed the last 2 dives were not synced, so I cleared my app data on the phone, now no dives are syncing.

Using the app in the play store

### Steps to reproduce:

Try syncing with cloud storage on your phone

### Current behavior:

No dives show up

### Expected behavior:

All dives show up as per web & desktop app

### Additional information:

Sync was working but stopped.

**Comment by dirkhh** [comment]
This is a known bug in Subsurface-mobile 3.0.3 on Android.
3.0.4 fixes this, but Google's random approval algorithm apparently hasn't managed to push that build to regular users. If you urgently need access, you can join the beta program (where that build is already available), otherwise wait a few hours / days / however long Google thinks you should wait and you'll get the update.
