### ISSUE TITLE
[Idea] Enhanced features for social network sharing (and divelog online)

### ISSUE THREAD

**Issue by Ghalr** [subsurface/subsurface#279]
Hello.

As suggested by @janmulder I would like to request some enhanced features for social network sharing.
- Social network: Facebook, Instagram, Tumblr, Twitter
- Online Dive Log: divelogs.de, logbook.diviac.com, diveboard.com

How to connect ?
- Preferences>SharingNetwork  such as "Subsurface cloud storage" form
- Share on>Connect to> Specific SocialNetwork / OnlineDiveLog
- Once connected , buttons are greyed out.
- Disconnect from>All or Specific SocialNetwork / OnlineDiveLog
- AutoDisconnect when Subsurface is closed

How to share ?
- Select divelogs
- Select which network website (All or Specific)
- Click "Share"

Enhanced feature:
- Date/Time/Duration/MaxDepth/Notes should be shared as default

**Comment by Ghalr** [comment]
#280

**Comment by Ghalr** [comment]
#253

**Comment by dirkhh** [comment]
Thanks for the suggestions.
Here are my thoughts:
- treating online dive logs and social networks the same seems wrong. With an online divelog we'd want a bidirectional connection (as we have for divelogs.de). A social network is "post only".
- while it shouldn't be all that hard to create Instagram/Tumblr/Twitter integrations, we are back to my standard answer... is there a developer interested in doing this?
- same is true for the other online dive logs, of course (but that tends to be more work because one would want this to be bidirectional)

All that said, I think there is a very valid core here, so I'll accept the idea as something we should do.
