### ISSUE TITLE
Failed to Parse Dive Log File

### ISSUE THREAD

**Issue by Davidwazza** [subsurface/subsurface#2955]
### Describe the issue:
I don't think I shut down Subsurface correctly (left open with dive log whilst I closed my Surface Pro). When I next opened Subsurface, it mentions that it failed to parse my dive log file, attached.
Can anyone see the issue in this file / allow it to be fixed. Unfortunately, I hadn't thought to backup the file, and so has all my data in there. Thanks!

### Operating system:
Microsoft Surface Pro 6
Microsoft Windows 10 Home

### Subsurface version:
Subsurface version 4.9.6

[Dive Log.zip](https://github.com/subsurface/subsurface/files/5228467/Dive.Log.zip)

**Comment by atdotde** [comment]
I don't think there is a problem due to turning of your Surface Pro. What appears to be wrong is that in you latest dive, you use two pressure sensors and somehow they got mixed up: In the file you sent, there are samples that have two values for "pressure0" rather than one for one sensor and the other for the other sensor. I changed those such that the second value is now assigned to your second sensor and then Subsurface can read your file again but judging from the pressure lines, the values are mixed up. (see attachment)
Could you try try to delete this last dive and download it once more? If this results in the same problem, we need to look into the download code how the mix up of sensors comes about.
[david1.txt](https://github.com/subsurface/subsurface/files/5230038/david1.txt)
