### ISSUE TITLE
Dive import, duration sometimes show seconds (even 00 seconds)

### ISSUE THREAD

**Issue by SamuelBenard** [subsurface/subsurface#362]
After import, some times, dive duration is in format minutes:seconds, sometimes not.

On this screenshot, you can see dives 630, 640, 653 respectively have a duration of 3m20s, 8m00s, 13m00s while all the others just have a number of minutes with no seconds. The time format should be constant. Either minutes or hours:minutes or hours:minutes:seconds

![capture du 2017-04-29 11-05-16](https://cloud.githubusercontent.com/assets/1573802/25554716/49b2347a-2ccc-11e7-8435-3f607346cd98.png)

**Comment by Ghalr** [comment]
I would prefer in minutes.

**Comment by dirkhh** [comment]
This is tricky. Because different divers want different things. Freedivers want minutes and seconds. Cave divers want hours and minutes. Recreational divers most likely would be fine with minutes only.
I'd have to look at the code, but IIRC right now we give you hours when it's more than 60 minutes and we give you seconds when it's fewer than 15 minutes.
Yes, of course. We could add yet another setting. But remember, every setting makes the software harder to use for a beginner, requires more testing, more translation, introduces more bugs. So I'm not too keen on that.

**Comment by sfuchs79** [comment]
For one part of this I see a simple solution w/o additional prefs option:
Instead of deciding based on a 15min threshold to use "MMmSSs" format for short dives we could do this based on dive mode for an existing dive. There we can select "Freedive" already today.

For minutes versus hours and minutes it might be very difficult to avoid a preferences option. Personally my friends and I meanwhile when we talk use to say: "Let's do a 75min/90min/100min/120min/... dive". So I would prefer this way. But I also know a guy who is regularly telling us that he did a 4 1/2 hours dive again... ;-)

**Comment by sfuchs79** [comment]
Ah, we even have this already here but in "or" combination with the 15min threshold:
https://github.com/Subsurface-divelog/subsurface/blob/master/qt-models/divetripmodel.cpp#L356
Honestly I would remove the 15min thing.

**Comment by Ghalr** [comment]
I wonder if it is not easy (reading) to use Hmins to calculate.
Also this is the same, to summarize how many hours you made each months, better to use "days" notation

**Comment by sfuchs79** [comment]
I played around with different format options for scuba dives and freedives incl. taking into account the format of dive duration for the dive information tab and the question if I personally would also prefer to have the depth unit in the table.
My result is a little bit frustrating and I learn to understand @dirkhh better and better:
- I **am** able to find a solution and format I like :-)
- This even won't fit with what @Ghalr likes
- This for sure also won't fit with what thousands other users like
- No one really wants to have a config option for this minor thing

I'll wait for s.o. having a really great idea... unless s.th. asks me personally for my prefered option ;-)

**Comment by SamuelBenard** [comment]
To me it's a question of consistency. It's not because I dive less than 15minutes or more than 1h that it should change the way duration is displayed. In settings, we already have units / Time units where we could put such setting. I understand that every setting makes the software harder to use. But in this case, we are just talking of a setting. Almost no algorithm/code as the actual code seems to be ready to such display change which means very small space for bug. I agree, it's more work for translators and for others. But isn't this software meant to evolve anyway ?

We all have different needs. Freedivers, divers, tec divers, etc. Actually, we tell them that we have one display that's not ideal but should be suitable for most and they have to deal with it.

To be 100% honnest, I can deal with it. Especially now that I know the 15min and 1h rule.
