### ISSUE TITLE
4.6.4: Multi-select "Add dive(s) to trip below" not working

### ISSUE THREAD

**Issue by madscientist** [subsurface/subsurface#522]
Subsurface 4.6.4 / Linux

I have a trip from this month (imported from my dive computer).  Then I created a dive from last year by hand, then made a new trip for that.  Now when I create new dives by hand they appear below this month's trip and above last year's trip, outside of either trip (I can't seem to find a way to have the dive be automatically added to a given trip upon creation).  If I select one dive and right-click "Add dive(s) to trip below" it works fine.

Also if I created two dives (by hand) and selected both of them and used "Add dive(s) to trip below" that worked (the one time I tried it).

But if I create three dives or four dives (haven't tried other numbers) without moving any of them, and select either all of them or the bottom two or three, then select "Add dive(s) to trip below", nothing happens: the dives don't move.  I have to select them one at a time, starting with the bottom one, and move them to the trip below.

**Comment by janmulder** [comment]
Did some research in this issue. It leads back to an ancient (3 year old) commit 512c42e38aec. Not sure this issue is introduced here, but that's not relevant now. I believe this (erroneous) behavior is here for a very long time.

Key in reproducing all this is the location where the context menu is requested (using the right mouse button). When it is the row next to the trip, the add-to-trip succeeds correctly, otherwise it  is a no-op.

In this code fragment:

```
struct dive *d = (struct dive *)contextMenuIndex.data(DiveTripModel::DIVE_ROLE).value<void *>();
QModelIndex t = contextMenuIndex.sibling(contextMenuIndex.row() + delta, 0);
dive_trip_t *trip = (dive_trip_t *)t.data(DiveTripModel::TRIP_ROLE).value<void *>();
```
the *trip pointer is NULL when popping up the context menu on  a different (ie. not the closest) row. 

However, I do not see an easy fix, and a 3 year old (evident) bug does not seem high prio.
