### ISSUE TITLE
Presentation error since 4.7.1

### ISSUE THREAD

**Issue by fkmuck1** [subsurface/subsurface#776]
### Describe the issue:

- X Bug
- [ ] Change request
- [ ] New feature request
- [ ] Discussion request

### Issue long description:
Since Version 4.7.1 i have a huge presentation error.
1.  I am unable to see the menu bar.
2. All rows are offset by one line (i have to click one line below the field i want to activate)

### Operating system:
Windows 10 Pro, 64 bit, Build 1709
Dell XPS 15 9560 with 4K Monitor

### Subsurface version:
Current 4.7.2
Error since 4.7.1
Official Windows release
Before 4.7.1 i didnt had this problem

### Steps to reproduce:
Maybe to use a 4 K Monitor?

### Additional information:
I tried to use compatibilty mode for some other Windows versions  with no result.
I tried different behavior settings with no result (scale 640x480, disable high DPI-scale behavior, fullscreen optimization, run as administratior).
Reinstalled the program already.
Maybe the program has problems with my 4 K Monitor?

English is not my native language. Maybe i can provide more detailed and better informations in german :)

### Mentions:

![image](https://user-images.githubusercontent.com/33388198/32412821-e6def766-c203-11e7-9e8f-49305878f5e1.png)

![image](https://user-images.githubusercontent.com/33388198/32412824-00bf3902-c204-11e7-95f5-acf43f8e0e19.png)

**Comment by neolit123** [comment]
that's very strange...
have you tried changing the Windows 10 font scale like so: https://img.gadgethacks.com/img/24/71/63584672105505/0/change-font-size-windows-10.w1456.jpg)
(not sure if your comment about ` disable high DPI-scale behavior` means fonts scale.)

other than that i'm out of ideas. also, i don't see how this issue is only present in `4.7.2`

here is something else to try - NOTE!!! **do at your own risk, this can delete your Subsurface settings if you delete the registry key**
- exit Subsurface
- open the start menu and start `Regedit`
- navigate to HKEY_CURRENT_USER -> Software
- rename `Subsurface` with F2 to something like `Subsurface_`
- start Subsurface
- see if this fixes it

if it doesn't fix it rename delete the new `Subsurface` registry entry and rename `Subsurface_` back to `Subsurface`.

**Comment by neolit123** [comment]
> Before 4.7.1 i didn't had this problem

oh, so it's before 4.7.1.

**Comment by neolit123** [comment]
you can also try deleting/renaming only this reg. key:
`HKEY_CURRENT_USER -> Software -> Subsurface -> Subsurface -> MainWindow`

**Comment by fkmuck1** [comment]
I uninstalled Subsurface again and deleted the registry key 
HKEY_CURRENT_USER -> Software -> Subsurface
But no result. Still missing the menu bar.

Also tryed to play with the scaling you mean but with no result.

The settings i meant is when you right click on subsurface.exe an then go to properties.
I played with all possible options but the menu bar doesnt come back.
![image](https://user-images.githubusercontent.com/33388198/32458258-2112218c-c32c-11e7-9a84-ea62fc576c8b.png)

I found an older install file of subsurface on my computer => 4.6.2 , and installed it.
In this version i can see the menu bar !!!
So there must be something new or different in 4.7.1 and 4.7.2 which cause this behavior.
Here you can see the difference.
![image](https://user-images.githubusercontent.com/33388198/32458899-2880ed8e-c32e-11e7-93d3-5603e17da1c4.png)
![image](https://user-images.githubusercontent.com/33388198/32459058-b959b188-c32e-11e7-84ae-6f7cb4bd888a.png)


Maybe you can find the reason?

**Comment by tcanabrava** [comment]
There's no preferences to set the menubar on subsurface, in the code we
never remove it.
I'll poke here a bit to see what I can find.

**Comment by ijdod** [comment]
I'm seeing the same issue since v4.7.1 and still with 4.7.4. Also on a 4K monitor. Windows scaling is at 200%, but none of the suggestions above fix the problem. Changing the display resution to FullHD doesn't help either (cleared the MainWindow key before starting).

**Comment by neolit123** [comment]
@ijdod are you sure this happened when you installed 4.7.1 for the first time?
did it work OK with 4.7.0?

**Comment by ijdod** [comment]
I went from 4.6.4 (which worked fine) directly to 4.7.1, which had the problem. I have not tried 4.7.0.

**Comment by neolit123** [comment]
@ijdod 
i will make an installer for you test in a minute, so that we can find the cause.

**Comment by neolit123** [comment]
@ijdod 
i've started our build system to create a test installer here:
https://github.com/Subsurface-divelog/subsurface/pull/842

it contains a small change that might be a fix for the 4k issues.
it would take around 20 minutes for the build setup to finish.
when it's done i will send you another message for you to download it and test it.

thanks

**Comment by neolit123** [comment]
@ijdod 

please, download the installer from here:
https://transfer.sh/LwfAn/subsurface-4.7.4-75-gc88cd7834443.exe

you might have to do it quickly before it's gone as it's probably temporary.

you can also backup your existing folder by renaming it to `Subsurface_` and installing this to `Subsurface` once done testing you can restore your original Subsurface installation.

let me know if this fixes the issue?

P.S. this log right here proves that the installer originated from the subsurface CI system and not from me with malicious intents:
https://api.travis-ci.org/jobs/304981817/log.txt?deansi=true

near the end there is a:
```
+++bash ./upload.sh subsurface-4.7.4-75-gc88cd7834443.exe subsurface.exe subsurface.exe.debug
```

**Comment by ijdod** [comment]
Same problem.

**Comment by neolit123** [comment]
@ijdod 

thanks for testing.

sadly, i'm out of ideas at this point.
there are something like 1200+ changes (commits) between 4.6.4 and 4.7.4, so i don't know what could have caused that (yet, not many touch the main window).

i've tried reverting a more resent change, but to me this might be a Qt bug (Qt is the framework taht we are using). so a fix might be difficult to obtain any time soon.

**Comment by ijdod** [comment]
Thanks for trying. Looks like 4.7.0 wasn't released through the main site, versions there jump from 4.6.4 straight to 4.7.1. This is also where the issues started.

**Comment by ijdod** [comment]
Just as confirmation: 4.7.5 didn't fix the problem (didn't expect it to, but still :D)

**Comment by neolit123** [comment]
maybe this would be fixed once we move to a new Qt version.
the bug seems to be outside of Subsurface.

**Comment by vinsanity0** [comment]
Just a note. I'm also having the same problem on my Thinkpad T470 with Windows 10 and Subsurface 4.7.6. I tried the same things that are above.

Thanks for your hard work guys!! I'll use my MAC until QT fixes it. :-)

**Comment by MarioSDR93** [comment]
I have the same problem with Subsurface 4.7.7 on a Dell XPS 15 9560 with 4K Display

I have tried the following combinarion of resolution and scaling factor with no sucess:
1920x1080/100%
1920x1080/200%
3840x2160/100%
3840x2160/250%

**Comment by MarioSDR93** [comment]
![subsurface_plan_dive_4k_hidpi](https://user-images.githubusercontent.com/5072885/38616938-f5a0d5b8-3d95-11e8-861b-3e2dab2dedea.png)

@neolit123 

I just tried different screens of Subsurface and discovered, everything looks fine in the dive planning.

Maybe the issue is not in QT?

As soon as i hit cancel an go back to the normal screen the layout is broken again.

**Comment by neolit123** [comment]
@MarioGeckler 

i still think it's a Qt issue. i don't think we are doing anything "outside of the box".
maybe there is a way to avoid the issue, but hard to find a way to do that without a developer reproducing it.

**Comment by MarioSDR93** [comment]
@neolit123 

I fixed the issue for me:

I had the same issue in Blender, which doesnt use Qt at all.

The following steps fixed the issue for me.

- Open Device Manager
- Right Click Display Adapters -> Intel HD Graphics
- Properties -> Driver tab -> Update Driver button
- Use the "List of drivers on my computer" option
- Set to Microsoft Basic Driver. Note, your graphics may now be quite wonky because they aren't using the GPU...
- Install the new driver from Intel.
- Reboot.
- Done!

It looks like the vendor driver (Dell in my case) for the intel GPU is causing the issue.

[Source](https://developer.blender.org/T51521)

**Comment by ijdod** [comment]
The solution described by MarioGeckler solved the problem for me. For my HP laptop an Intel HD video driver update was available through HP.

**Comment by neolit123** [comment]
good to hear that a solution was found!
closing this ticket.
thanks.
